version: "3.4"

services:
  python:
    build:
      context: "../python"
      dockerfile: "../python/docker/Dockerfile"
    restart: always
    volumes:
      - "../python:/python"
    ports:
      - "5000:5000"
